name: Tracker ticket link

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: tracker-ticket-link
    runs-on:
      - self-hosted
      - linux
      - qyp
    steps:
      - uses: actions/checkout@v4
      - name: link ticket
        run: scripts/tracker-ticket-link.sh
        env:
          ST_OAUTH_TOKEN: ${{ secrets.ST_OAUTH_TOKEN }}
          ST_SERVER_ENDPOINT: ${{ vars.ST_SERVER_ENDPOINT }}
          BRANCH_NAME: ${{ github.head_ref }}
          BUILD_PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BODY: ${{ github.event.pull_request.body }}
          GH_REPO: ${{ github.repository }}
